# Generated by Django 5.2.15 on 2026-07-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(default='Descripcion de categoria', max_length=250),
            preserve_default=False,
        ),
    ]
