# Generated by Django 5.2.15 on 2026-07-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuma', '0002_categoria_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria_id',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria_id',
            field=models.ManyToManyField(related_name='productos', to='kuma.categoria'),
        ),
    ]
