# Generated by Django 5.2.15 on 2026-07-16 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuma', '0003_remove_producto_categoria_id_producto_categoria_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria_id',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='kuma.categoria'),
            preserve_default=False,
        ),
    ]
